In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("nassau_candy.csv")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [14]:



# Required columns available in the original dataset
required = [
    "Row ID",
    "Order ID",
    "Order Date",
    "Ship Date",
    "State/Province",
    "Ship Mode",
    "Sales",
    "Gross Profit"
]

# Check for missing required columns
missing_columns = [
    c for c in required if c not in df.columns
]

if missing_columns:
    raise ValueError(
        f"Missing required columns: {missing_columns}"
    )

# Convert date columns into datetime format
df["Order_Date"] = pd.to_datetime(
    df["Order Date"], errors="coerce"
)

df["Ship_Date"] = pd.to_datetime(
    df["Ship Date"], errors="coerce"
)

# Calculate shipping lead time in days
df["Shipping_Lead_Time_Days"] = (
    df["Ship_Date"] - df["Order_Date"]
).dt.days

# Validate the dataset
print("Rows:", len(df))

print(
    "Invalid dates:",
    df["Order_Date"].isna().sum()
    + df["Ship_Date"].isna().sum()
)

print(
    "Negative lead times:",
    (df["Shipping_Lead_Time_Days"] < 0).sum()
)

# Display actual available columns
print("\nAvailable columns:")
print(df.columns.tolist())

# Preview the validated data
display(df.head())

Rows: 10194
Invalid dates: 6064
Negative lead times: 0

Available columns:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Country/Region', 'City', 'State/Province', 'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name', 'Sales', 'Units', 'Gross Profit', 'Cost', 'Order_Date', 'Ship_Date', 'Shipping_Lead_Time_Days']

C:\Users\Ravindra Pal\AppData\Local\Temp\ipykernel_6444\3340540828.py:28: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Ship_Date"] = pd.to_datetime(

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Order_Date,Ship_Date,Shipping_Lead_Time_Days
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,...,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,2024-03-01,2026-06-30,851.0
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,...,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,2024-04-01,2026-07-01,821.0
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,...,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,2024-04-01,2026-07-01,821.0
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,...,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,2024-04-01,2026-07-01,821.0
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,...,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,2024-05-01,2026-07-05,795.0

In [15]:



# Required columns available in the original dataset
required = [
    "Row ID",
    "Order ID",
    "Order Date",
    "Ship Date",
    "State/Province",
    "Ship Mode",
    "Sales",
    "Gross Profit"
]

# Check for missing required columns
missing_columns = [
    c for c in required if c not in df.columns
]

if missing_columns:
    raise ValueError(
        f"Missing required columns: {missing_columns}"
    )

# Convert date columns into datetime format
df["Order_Date"] = pd.to_datetime(
    df["Order Date"], errors="coerce"
)

df["Ship_Date"] = pd.to_datetime(
    df["Ship Date"], errors="coerce"
)

# Calculate shipping lead time in days
df["Shipping_Lead_Time_Days"] = (
    df["Ship_Date"] - df["Order_Date"]
).dt.days

# Validate the dataset
print("Rows:", len(df))

print(
    "Invalid dates:",
    df["Order_Date"].isna().sum()
    + df["Ship_Date"].isna().sum()
)

print(
    "Negative lead times:",
    (df["Shipping_Lead_Time_Days"] < 0).sum()
)

# Display actual available columns
print("\nAvailable columns:")
print(df.columns.tolist())

# Preview the validated data
display(df.head())

Rows: 10194
Invalid dates: 6064
Negative lead times: 0

Available columns:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Country/Region', 'City', 'State/Province', 'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name', 'Sales', 'Units', 'Gross Profit', 'Cost', 'Order_Date', 'Ship_Date', 'Shipping_Lead_Time_Days']

C:\Users\Ravindra Pal\AppData\Local\Temp\ipykernel_6444\3340540828.py:28: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Ship_Date"] = pd.to_datetime(

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Order_Date,Ship_Date,Shipping_Lead_Time_Days
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,...,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,2024-03-01,2026-06-30,851.0
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,...,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,2024-04-01,2026-07-01,821.0
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,...,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,2024-04-01,2026-07-01,821.0
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,...,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,2024-04-01,2026-07-01,821.0
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,...,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,2024-05-01,2026-07-05,795.0

In [16]:

# Step 1: Filter valid records
valid = df.loc[
    df["Order_Date"].notna()
    & df["Ship_Date"].notna()
    & df["Shipping_Lead_Time_Days"].notna()
    & (df["Shipping_Lead_Time_Days"] >= 0)
    & df["City"].notna()
    & df["State/Province"].notna()
].copy()

# Step 2: Create a geographic group
valid["Route"] = (
    valid["City"].astype(str).str.strip()
    + " -> "
    + valid["State/Province"].astype(str).str.strip()
)

# Step 3: Calculate geographic-group metrics
route_metrics = (
    valid.groupby("Route")
    .agg(
        Record_Count=("Row ID", "count"),
        Distinct_Orders=("Order ID", "nunique"),
        Mean_Lead_Time=("Shipping_Lead_Time_Days", "mean"),
        Median_Lead_Time=("Shipping_Lead_Time_Days", "median"),
        Lead_Time_Std=("Shipping_Lead_Time_Days", "std"),
        P90_Lead_Time=(
            "Shipping_Lead_Time_Days",
            lambda x: x.quantile(0.90)
        ),
        Sales=("Sales", "sum"),
        Gross_Profit=("Gross Profit", "sum")
    )
    .reset_index()
)

# Step 4: Round lead-time metrics
metric_columns = [
    "Mean_Lead_Time",
    "Median_Lead_Time",
    "Lead_Time_Std",
    "P90_Lead_Time"
]

route_metrics[metric_columns] = (
    route_metrics[metric_columns].round(2)
)

# Step 5: Sort by record volume
route_metrics = route_metrics.sort_values(
    "Record_Count",
    ascending=False
)

# Step 6: Display the results
display(route_metrics.head(10))

,Route,Record_Count,Distinct_Orders,Mean_Lead_Time,Median_Lead_Time,Lead_Time_Std,P90_Lead_Time,Sales,Gross_Profit
279,New York City -> New York,391,321,1397.18,1359.0,268.68,1818.0,5106.73,3341.14
227,Los Angeles -> California,288,245,1381.54,1448.0,296.19,1728.0,3985.31,2676.23
317,Philadelphia -> Pennsylvania,223,181,1399.33,1389.0,299.08,1833.0,2926.21,1916.79
374,San Francisco -> California,199,169,1376.18,1393.0,316.75,1783.0,2709.28,1813.92
382,Seattle -> Washington,178,147,1401.18,1452.0,334.73,1871.2,2449.15,1626.13
175,Houston -> Texas,167,142,1282.96,1301.0,272.17,1691.4,2597.77,1686.17
69,Chicago -> Illinois,118,101,1354.60,1333.0,288.59,1785.0,1687.27,1098.57
97,Dallas -> Texas,73,60,1413.18,1364.0,235.16,1699.0,978.99,660.17
373,San Diego -> California,66,61,1351.62,1392.0,309.74,1700.5,937.14,621.90
107,Detroit -> Michigan,53,39,1400.38,1404.0,241.36,1725.0,682.80,459.96

In [17]:

# Define a minimum record threshold only if justified
# by the project brief or supervisor.
MIN_RECORDS = None

# Use the geographic-group metrics calculated earlier
eligible_routes = route_metrics.copy()

# Apply the threshold only when one is specified
if MIN_RECORDS is not None:
    eligible_routes = eligible_routes.loc[
        eligible_routes["Record_Count"] >= MIN_RECORDS
    ].copy()

# Identify geographic groups with the shortest median lead time
fastest_routes = (
    eligible_routes
    .sort_values(
        ["Median_Lead_Time", "Record_Count"],
        ascending=[True, False]
    )
    .head(10)
)

# Identify geographic groups with the longest median lead time
slowest_routes = (
    eligible_routes
    .sort_values(
        ["Median_Lead_Time", "Record_Count"],
        ascending=[False, False]
    )
    .head(10)
)

print("10 Geographic Groups with the Shortest Median Lead Time")
display(fastest_routes)

print("10 Geographic Groups with the Longest Median Lead Time")
display(slowest_routes)

10 Geographic Groups with the Shortest Median Lead Time

,Route,Record_Count,Distinct_Orders,Mean_Lead_Time,Median_Lead_Time,Lead_Time_Std,P90_Lead_Time,Sales,Gross_Profit
81,Columbia -> Missouri,6,3,644.00,644.0,0.00,644.0,50.97,34.67
211,Laredo -> Texas,3,2,931.00,673.0,446.87,1292.2,22.35,14.75
221,Lodi -> California,1,1,674.00,674.0,NaN,674.0,6.98,4.98
218,Lewiston -> Idaho,1,1,702.00,702.0,NaN,702.0,3.60,2.40
151,Great Falls -> Montana,3,2,704.00,704.0,0.00,704.0,53.25,34.71
216,League City -> Texas,6,4,1062.00,760.0,467.86,1666.0,89.78,62.18
219,Linden -> New Jersey,1,1,764.00,764.0,NaN,764.0,25.20,16.80
338,Redondo Beach -> California,8,6,967.12,775.5,356.15,1389.0,119.61,80.43
451,Woodstock -> Georgia,2,2,787.00,787.0,0.00,787.0,55.12,38.70
283,Niagara Falls -> New York,1,1,788.00,788.0,NaN,788.0,11.25,7.35

10 Geographic Groups with the Longest Median Lead Time

,Route,Record_Count,Distinct_Orders,Mean_Lead_Time,Median_Lead_Time,Lead_Time_Std,P90_Lead_Time,Sales,Gross_Profit
361,Saginaw -> Michigan,5,4,1964.00,1964.0,0.00,1964.0,70.66,49.12
103,Denver -> Colorado,23,17,1573.52,1932.0,444.91,1962.0,362.83,227.69
125,Everett -> Massachusetts,3,2,1765.67,1932.0,288.10,1932.0,59.25,38.95
34,Bellingham -> Washington,3,3,1863.67,1931.0,116.62,1931.0,89.25,59.05
149,Grand Prairie -> Texas,4,3,1813.25,1905.5,228.46,1962.0,55.20,36.90
407,Thornton -> Colorado,9,5,1860.11,1904.0,131.67,1904.0,139.39,92.45
369,Salt Lake City -> Utah,1,1,1904.00,1904.0,NaN,1904.0,10.47,7.47
302,Overland Park -> Kansas,2,2,1903.00,1903.0,0.00,1903.0,29.97,20.13
363,Saint Louis -> Missouri,3,3,1659.00,1902.0,420.89,1902.0,57.38,39.58
98,Danville -> California,6,6,1901.00,1901.0,0.00,1901.0,208.95,113.53

In [18]:

from pathlib import Path

# Create the output directory for Day 06
output_dir = Path("outputs/day_06")
output_dir.mkdir(parents=True, exist_ok=True)

# Save geographic-group efficiency metrics
route_metrics.to_csv(
    output_dir / "geographic_group_efficiency_metrics.csv",
    index=False
)

# Save the 10 geographic groups with the shortest median lead time
fastest_routes.to_csv(
    output_dir / "top_10_fastest_geographic_groups.csv",
    index=False
)

# Save the 10 geographic groups with the longest median lead time
slowest_routes.to_csv(
    output_dir / "top_10_slowest_geographic_groups.csv",
    index=False
)

print("Day 06 benchmark outputs saved to:", output_dir.resolve())
print("Files created:")
print("- geographic_group_efficiency_metrics.csv")
print("- top_10_fastest_geographic_groups.csv")
print("- top_10_slowest_geographic_groups.csv")

Day 06 benchmark outputs saved to: D:\Data Analytics\ReClasses\Internship Projects\Unified Mentor\Project 1\3.Python\outputs\day_06
Files created:
- geographic_group_efficiency_metrics.csv
- top_10_fastest_geographic_groups.csv
- top_10_slowest_geographic_groups.csv